[package]
name = "non_structural_derive_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = "2.0.71"
proc-macro2 = "1.0.86"
synstructure.workspace = true

[lib]
proc-macro = true
