[package]
name = "non_structural_derive_macro"
description.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
quote = "1.0.36"
syn = "2.0.71"
proc-macro2 = "1.0.86"
synstructure = "0.13.1"

[lib]
proc-macro = true
